const prep2ExamOne = [
  {
    id: 1,
    choose: "You ....... look right and left before you cross the road.",
    answor1: "has to",
    answor2: "must",
    answor3: "mustn't",
    answor4: "can't",
    answorTrue: "must",
  },
  {
    id: 2,
    choose: "When did Ali ....... that book?",
    answor1: "buy",
    answor2: "bought",
    answor3: "buys",
    answor4: "brought",
    answorTrue: "buy",
  },
  {
    id: 3,
    choose: "mona ....... to school yesterday because she was ill.",
    answor1: "not come",
    answor2: "doesn't come",
    answor3: "don't come",
    answor4: "didn't come",
    answorTrue: "didn't come",
  },
  {
    id: 4,
    choose: "I'm hungry. I think ....... a sandwich.",
    answor1: "I have",
    answor2: "I'm going to have",
    answor3: "I'll have",
    answor4: "I had",
    answorTrue: "I'll have",
  },
  {
    id: 5,
    choose: "Go up the stairs. The laboratory is on the first ....... .",
    answor1: "gate",
    answor2: "door",
    answor3: "flour",
    answor4: "floor",
    answorTrue: "floor",
  },
  {
    id: 6,
    choose:
      "It is best to ....... your school bag the night before you go to school.",
    answor1: "pack",
    answor2: "place",
    answor3: "put",
    answor4: "plan",
    answorTrue: "pack",
  },
  {
    id: 7,
    choose: "On my new ....... I can see that we have Englesh in the morning.",
    answor1: "corridor",
    answor2: "timetable",
    answor3: "map",
    answor4: "location",
    answorTrue: "timetable",
  },
  {
    id: 8,
    choose: "Sunglasses can ....... your eyes from the sun.",
    answor1: "pour",
    answor2: "peel",
    answor3: "protect",
    answor4: "put",
    answorTrue: "protect",
  },
  {
    id: 9,
    choose:
      "You ....... stay in the library after six o'clock because it closes then.",
    answor1: "must",
    answor2: "can't",
    answor3: "can",
    answor4: "did",
    answorTrue: "can't",
  },
  {
    id: 10,
    choose: "lock, Grandma is carrying a lot of begs. I ....... her.",
    answor1: "going to help",
    answor2: "will help",
    answor3: "help",
    answor4: "didn't help",
    answorTrue: "will help",
  },
];

export { prep2ExamOne };
